# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Id', models.CharField(blank=True, max_length=250, null=True)),
                ('quantity', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=250, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Id', models.CharField(blank=True, max_length=250, null=True)),
                ('Productname', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=250, null=True)),
                ('stock', models.CharField(blank=True, max_length=250, null=True)),
                ('imageurl', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('unit', models.CharField(blank=True, max_length=250, null=True)),
                ('colour', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=250, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
